name: MAIN

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual workflow dispatch
  workflow_dispatch:
  
  # Trigger on push to main branches
  push:
    branches:
      - main
      - master

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # GitHub Profile Summary Cards
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      # GitHub Streak Stats
      - name: Generate GitHub Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@master
        with:
          github_user: ${{ github.repository_owner }}

      # GitHub Stats
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Vaibhavbasidoni
          show_icons: true
          theme: radical

      # Contribution Graph
      - name: Generate Contribution Graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          username: Vaibhavbasidoni
          theme: react

      # Commit and Push Changes
      - name: Commit and Push Updates
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update GitHub profile metrics" || exit 0
          git push
