name: Generate Snake Contribution Grid

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job in the repository actions section
  workflow_dispatch:
  
  # run on every push on the master/main branch
  push:
    branches:
    - master
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<username>) contributions graph
      - name: Generate GitHub Snake Grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Vaibhavbasidoni
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif

      # push the content of <build-dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<username>/<repository>/<target-branch>/
      - name: Push GitHub Snake Grid to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
